import proj4 from 'proj4';

const ARCGIS='https://services.arcgis.com/VU1dOESuQS3Z8oTW/ArcGIS/rest/services/Drzewa_do_piel%C4%99gnacji_2023_zewn%C4%99trzna/FeatureServer/12/query';
const FF='https://fallingfruit.org/api/0.3';
const FF_KEY='AKDJGHSD';
const WARSAW_IMPORT='Drzewa w Warszawie';
const WFS_SERVICES=['https://wms2.um.warszawa.pl/geoserver/wfs/wfs','http://wms2.um.warszawa.pl/geoserver/wfs/wfs','https://wfs.um.warszawa.pl/serwis'];
const WGS84='EPSG:4326';
proj4.defs('EPSG:2178','+proj=tmerc +lat_0=0 +lon_0=21 +k=0.999923 +x_0=7500000 +y_0=0 +ellps=GRS80 +units=m +no_defs +type=crs');

const rad=x=>x*Math.PI/180,deg=x=>x*180/Math.PI;
function hav(a,b){const R=6371000,dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon),s=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(s));}
function bearing(a,b){const y=Math.sin(rad(b.lon-a.lon))*Math.cos(rad(b.lat)),x=Math.cos(rad(a.lat))*Math.sin(rad(b.lat))-Math.sin(rad(a.lat))*Math.cos(rad(b.lat))*Math.cos(rad(b.lon-a.lon));return(deg(Math.atan2(y,x))+360)%360;}
function norm180(x){return((x+540)%360)-180;}
function compass(b){return['N','NE','E','SE','S','SW','W','NW'][Math.round(b/45)%8];}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null;}
function firstProp(p,re){const k=Object.keys(p||{}).find(x=>re.test(x));return k?p[k]:null;}
function decorate(target,p,source,extra={}){const d=hav(target,p),b=bearing(target,p);return{id:extra.id??null,species:extra.species??null,lat:p.lat,lon:p.lon,distance_m:+d.toFixed(2),bearing_deg:+b.toFixed(1),bearing_compass:compass(b),source,verified:false,...extra};}
function annotateView(candidates,camera,heading,fov=100){if(!camera||!Number.isFinite(heading))return candidates;const visible=[];for(const c of candidates){const b=bearing(camera,c),rel=norm180(b-heading);c.camera_bearing_deg=+b.toFixed(1);c.relative_view_angle_deg=+rel.toFixed(1);c.in_camera_fov=Math.abs(rel)<=Math.max(30,Math.min(160,fov))/2;if(c.in_camera_fov)visible.push(c);}visible.sort((a,b)=>b.relative_view_angle_deg-a.relative_view_angle_deg);visible.forEach((c,i)=>c.view_index_from_right=i+1);return candidates;}

async function arcgis(target,radius){const q=new URLSearchParams({where:'1=1',geometry:`${target.lon},${target.lat}`,geometryType:'esriGeometryPoint',inSR:'4326',spatialRel:'esriSpatialRelIntersects',distance:String(radius),units:'esriSRUnit_Meter',outFields:'*',returnGeometry:'true',outSR:'4326',f:'json'});const r=await fetch(`${ARCGIS}?${q}`,{headers:{'user-agent':'OSINT-Navigator/0.5'},signal:AbortSignal.timeout(7000)});if(!r.ok)throw new Error(`ArcGIS HTTP ${r.status}`);const j=await r.json();if(j.error)throw new Error(j.error.message||'ArcGIS error');const out=[];for(const f of j.features||[]){const x=Number(f.geometry?.x),y=Number(f.geometry?.y);if(!Number.isFinite(x)||!Number.isFinite(y))continue;const p={lat:y,lon:x},d=hav(target,p);if(d>radius)continue;const a=f.attributes||{};out.push(decorate(target,p,'ARCGIS_MOKOTOW_2019',{id:firstProp(a,/OBJECTID|^id$/i),species:firstProp(a,/gatunek|species|nazwa/i),properties:a}));}return out.sort((a,b)=>a.distance_m-b.distance_m);}

async function fallingFruit(target,radius){const searchRadius=Math.max(radius,100),latD=searchRadius/111320,lonD=searchRadius/(111320*Math.max(.2,Math.cos(rad(target.lat))));const bounds=`${target.lat-latD},${target.lon-lonD}|${target.lat+latD},${target.lon+lonD}`;const q=new URLSearchParams({api_key:FF_KEY,bounds,center:`${target.lat},${target.lon}`,muni:'true',limit:'40'});const r=await fetch(`${FF}/locations?${q}`,{headers:{'user-agent':'OSINT-Navigator/0.5'},signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error(`Falling Fruit HTTP ${r.status}`);const list=await r.json();const details=await Promise.all((Array.isArray(list)?list:[]).slice(0,24).map(async item=>{try{const d=await fetch(`${FF}/locations/${item.id}?api_key=${FF_KEY}&embed=import`,{headers:{'user-agent':'OSINT-Navigator/0.5'},signal:AbortSignal.timeout(4500)});return d.ok?{item,detail:await d.json()}:null;}catch{return null;}}));const all=[];for(const row of details){if(!row||row.detail?.muni!==true||row.detail?.import?.name!==WARSAW_IMPORT)continue;const p={lat:Number(row.item.lat),lon:Number(row.item.lng)};if(!Number.isFinite(p.lat)||!Number.isFinite(p.lon))continue;const c=decorate(target,p,'FALLING_FRUIT_WARSAW_2016',{id:row.item.id,species:Array.isArray(row.item.type_names)?row.item.type_names.join(', '):null,source_age:'imported 2016-04-19; stale fallback',municipal_inventory:true,import:{id:row.detail.import.id,name:row.detail.import.name,created_at:row.detail.import.created_at,location_count:row.detail.import.location_count},detail:{address:row.detail.address||null,city:row.detail.city||null,unverified:row.detail.unverified??null,type_ids:row.item.type_ids||[]}});all.push(c);}all.sort((a,b)=>a.distance_m-b.distance_m);return{within:all.filter(x=>x.distance_m<=radius),all,raw_count:Array.isArray(list)?list.length:0};}

function clean(v=''){return String(v).replace(/<!\[CDATA\[|\]\]>/g,'').replace(/&amp;/g,'&').trim();}
async function wfs(target,radius){let svc=null,layer=null,attempts=[];for(const u of WFS_SERVICES){try{const r=await fetch(`${u}?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=1.1.0`,{headers:{'user-agent':'OSINT-Navigator/0.5'},signal:AbortSignal.timeout(3000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);const xml=await r.text(),m=[...xml.matchAll(/<(?:\w+:)?Name>([^<]*ZIELEN_DRZEWA[^<]*)<\/(?:\w+:)?Name>/gi)][0];if(!m)throw new Error('layer missing');svc=u;layer=clean(m[1]);break;}catch(e){attempts.push({url:u,error:e.message});}}if(!svc)return{candidates:[],attempts};const[x,y]=proj4(WGS84,'EPSG:2178',[target.lon,target.lat]),bbox=[x-radius,y-radius,x+radius,y+radius].join(',')+',EPSG:2178',q=new URLSearchParams({SERVICE:'WFS',VERSION:'1.1.0',REQUEST:'GetFeature',TYPENAME:layer,SRSNAME:'EPSG:2178',BBOX:bbox,MAXFEATURES:'100'}),r=await fetch(`${svc}?${q}`,{headers:{'user-agent':'OSINT-Navigator/0.5'},signal:AbortSignal.timeout(4500)});if(!r.ok)return{candidates:[],attempts:[...attempts,{url:svc,error:`HTTP ${r.status}`} ]};const xml=await r.text(),members=xml.match(/<(?:gml:)?featureMember\b[\s\S]*?<\/(?:gml:)?featureMember>/gi)||[],out=[];for(const m of members){const pm=m.match(/<(?:gml:)?pos(?:\s[^>]*)?>([^<]+)<\/(?:gml:)?pos>/i);if(!pm)continue;const n=(pm[1].match(/-?\d+(?:\.\d+)?/g)||[]).map(Number);if(n.length<2)continue;let lon,lat;try{[lon,lat]=proj4('EPSG:2178',WGS84,[n[0],n[1]])}catch{continue}const p={lat,lon};if(hav(target,p)>radius)continue;const props={};for(const x of m.matchAll(/<(?:[\w.-]+:)?([\w.-]+)(?:\s[^>]*)?>([^<>]{0,500})<\/(?:[\w.-]+:)?\1>/g))props[x[1]]=clean(x[2]);out.push(decorate(target,p,'WARSZAWA_WFS_ZIELEN_DRZEWA',{id:firstProp(props,/^(id|objectid|fid|ident|nr|numer)|(_id)$/i),species:firstProp(props,/gatunek|species|nazwa/i),properties:props}));}return{candidates:out.sort((a,b)=>a.distance_m-b.distance_m),attempts,service:svc,layer};}

export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(!['GET','POST'].includes(req.method)){res.setHeader('Allow','GET, POST');return res.status(405).json({error:'Method not allowed'});}const input=req.method==='GET'?req.query:(req.body||{}),target={lat:num(input.lat),lon:num(input.lon)},radius=Math.max(5,Math.min(120,num(input.radius_m)??80)),camera=(num(input.camera_lat)!==null&&num(input.camera_lon)!==null)?{lat:num(input.camera_lat),lon:num(input.camera_lon)}:null,heading=num(input.heading),fov=num(input.fov)??100;if(target.lat===null||target.lon===null||Math.abs(target.lat)>90||Math.abs(target.lon)>180)return res.status(400).json({error:'Invalid lat/lon'});const diagnostics=[];let candidates=[],source=null,nearest_outside=null;try{const a=await arcgis(target,radius);diagnostics.push({source:'ARCGIS_MOKOTOW_2019',ok:true,count:a.length});if(a.length){candidates=a;source={type:'ArcGIS REST',dataset:'Drzewa do pielęgnacji 2023'};}}catch(e){diagnostics.push({source:'ARCGIS_MOKOTOW_2019',ok:false,error:e.message});}if(!candidates.length){try{const ff=await fallingFruit(target,radius);diagnostics.push({source:'FALLING_FRUIT_WARSAW_2016',ok:true,count_within:ff.within.length,count_tree_records:ff.all.length,raw_count:ff.raw_count});candidates=ff.within;nearest_outside=ff.all.find(x=>x.distance_m>radius)||null;source={type:'Falling Fruit API',dataset:WARSAW_IMPORT,imported:'2016-04-19',freshness:'STALE_FALLBACK'};}catch(e){diagnostics.push({source:'FALLING_FRUIT_WARSAW_2016',ok:false,error:e.message});}}if(!candidates.length&&!nearest_outside){try{const w=await wfs(target,radius);diagnostics.push({source:'WARSZAWA_WFS',ok:true,count:w.candidates.length,attempts:w.attempts});candidates=w.candidates;source={type:'Warsaw WFS',service:w.service,layer:w.layer};}catch(e){diagnostics.push({source:'WARSZAWA_WFS',ok:false,error:e.message});}}
  annotateView(candidates,camera,heading,fov);if(nearest_outside)annotateView([nearest_outside],camera,heading,fov);
  const visible=candidates.filter(x=>x.in_camera_fov).sort((a,b)=>(a.view_index_from_right??999)-(b.view_index_from_right??999));
  const shortlist34=visible.filter(x=>x.view_index_from_right===3||x.view_index_from_right===4);
  const best=shortlist34[0]||candidates[0]||null;
  const status=best?(shortlist34.length?'TREE_VISUAL_ORDER_CANDIDATES':'TREE_CANDIDATES_FOUND'):(nearest_outside?'NO_TREE_WITHIN_RADIUS':'NO_USABLE_TREE_CANDIDATE');
  return res.status(200).json({status,query:{...target,radius_m:radius,camera,heading,fov},source,best,candidates:candidates.slice(0,20),visible_order_from_right:visible.map(x=>({id:x.id,lat:x.lat,lon:x.lon,distance_m:x.distance_m,relative_view_angle_deg:x.relative_view_angle_deg,view_index_from_right:x.view_index_from_right})),shortlist_3_or_4_from_right:shortlist34,nearest_outside,verification:{verified:false,rule:'Visual order and scene anchors outrank raw nearest-GIS distance; confirm with entrance/background geometry.'},diagnostics});}
